# Generated by Django 4.1.4 on 2023-04-03 02:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskomatic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('projectName', models.CharField(max_length=160)),
                ('projectDescription', models.CharField(max_length=350)),
                ('hasDeadline', models.BooleanField(default=False)),
                ('hasInventory', models.BooleanField(default=False)),
                ('hasTasks', models.BooleanField(default=False)),
                ('creationDate', models.DateField()),
                ('deadlineDate', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=160)),
                ('taskDescription', models.CharField(max_length=350)),
                ('taskDeadline', models.DateField(blank=True, null=True)),
                ('taskImportance', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('taskLimitAlert', models.DateField(blank=True, null=True)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskomatic.project')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=160)),
                ('itemDescription', models.CharField(max_length=350)),
                ('itemQty', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('itemUnit', models.CharField(choices=[('UNIT', 'unit(s)'), ('%', 'percent'), ('KG', 'kilogram(s)'), ('CM', 'centimeter(s)')], default='UNIT', max_length=20)),
                ('itemLimitAlert', models.IntegerField(blank=True, null=True)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskomatic.project')),
            ],
        ),
    ]
