# Generated by Django 4.1.4 on 2023-05-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskomatic', '0002_project_tasks_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='username',
            new_name='owner',
        ),
    ]
