# Generated by Django 4.1.4 on 2023-05-01 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskomatic', '0004_room_host_room_topic_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskCreator',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
