# Generated by Django 4.1.4 on 2023-05-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskomatic', '0007_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskCompletion',
            field=models.BooleanField(default=False),
        ),
    ]
